### ISSUE TITLE
Test 3: Completed

### ISSUE THREAD

**Issue by az-andresvejar** [front4Me/encryptedInstructionsTest#10]
Hola Santiago, te comparto el último feedback del challenge, ambos han sido completados, espera los siguientes pasos.
Saludos

Feedback 3: 07/Sep/2023
Casos de Prueba:
Problema 1: ts
P1-CP1-EntradaEjemplo: Pass
P1-CP2-EntradaCorrecta: Pass
P1-CP3-LongitudLinea1Invalida: Pass
P1-CP4-LongitudLinea2Invalida: Pass
P1-CP5-LongitudMensajeInvalido: Pass
P1-CP6-LongitudMensajeMenor3: Pass
P1-CP7-LongitudMensajeMayor5000: Pass
P1-CP8-LongitudInstruccion1Menor2: Pass
P1-CP9-LongitudInstruccion1Mayor50: Pass
P1-CP10-LongitudInstruccion2Menor2: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-CaracteresInvalidos: Pass
P1-CP13-DosInstruccionesEnMensaje: Pass
P1-CP14-Instruccion1CaracterRepetido: Pass
P1-CP15-InvalidFile: Pass

Problema 2: ts
P2-CP1-EntradaEjemplo: Pass
P2-CP2-R7_WP2: Pass
P2-CP3_R11_WP1: Pass
P2-CP4-RondasInvalidas: Pass
P2-CP5-RondasInvalidas-2: Pass
P2-CP6-CaracteresEnValorRondas: Pass
P2-CP7-CaraceresEnValorDeJugador: Pass
P2-CP8-RondasInvalidasMayor10k: Pass

**Comment by front4Me** [comment]
@az-andresvejar 
Gracias! fue un buen ejercicio, me gusto.
