### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by az-andresvejar** [front4Me/encryptedInstructionsTest#2]
Feedback 1: 01/Sep/2023
Problem 1: ts
- El problema no está correctamente entendido, existen condiciones no cubiertas, por favor revisar nuevamente.
- El problema requiere como salida un archivo.

Problema 2: ts
- El resultado del ganador no es correcto, es necesario revisar nuevamente el problema.
- Existen condiciones no cubiertas, por favor revisar nuevamente.

**Comment by front4Me** [comment]
@az-andresvejar this issue was solved in latest commit, thanks for the feedback!
