### ISSUE TITLE
Test 2

### ISSUE THREAD

**Issue by az-andresvejar** [front4Me/encryptedInstructionsTest#4]
- Gran parte de los escenarios están cubiertos, solo revisar el detalle del problema 1.
- El caso del problema 2 sigue son entenderse como debe determinarse el ganador, por favor revisa nuevamente.

Feedback 2: 05/Sep/2023
Casos de Prueba:
Problema 1: ts
P1-CP1-EntradaEjemplo: Pass
P1-CP2-EntradaCorrecta: Pass
P1-CP3-LongitudLinea1Invalida: Pass
P1-CP4-LongitudLinea2Invalida: Pass
P1-CP5-LongitudMensajeInvalido: Pass
P1-CP6-LongitudMensajeMenor3: Pass
P1-CP7-LongitudMensajeMayor5000: Pass
P1-CP8-LongitudInstruccion1Menor2: Pass
P1-CP9-LongitudInstruccion1Mayor50: Pass
P1-CP10-LongitudInstruccion2Menor2: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-CaracteresInvalidos: Pass
P1-CP13-DosInstruccionesEnMensaje: Fail
P1-CP14-Instruccion1CaracterRepetido: Pass
P1-CP15-InvalidFile: Fail
    - TypeError: Cannot read properties of undefined

Problema 2: ts
P2-CP1-EntradaEjemplo: Pass
P2-CP2-R7_WP2: Fail
P2-CP3_R11_WP1: Fail
P2-CP4-RondasInvalidas: Pass
P2-CP5-RondasInvalidas-2: Pass
P2-CP6-CaracteresEnValorRondas: Pass
P2-CP7-CaraceresEnValorDeJugador: Pass
P2-CP8-RondasInvalidasMayor10k: Pass
    - Revisar mensaje de salida: La instrucción 1 tiene que estar entre 2 y 50 caracteres

**Comment by front4Me** [comment]
@az-andresvejar , me podrias confirmar que el archivo con la explicación del problema sea el correcto,


<img width="753" alt="image" src="https://github.com/front4Me/encryptedInstructionsTest/assets/126296474/cbd970bf-6b68-45a4-8678-feef28f96b32">

<img width="753" alt="image" src="https://github.com/front4Me/encryptedInstructionsTest/assets/126296474/33859ad0-ea49-484c-9f25-0cb24ce8adad">

**Comment by front4Me** [comment]
@az-andresvejar asumiendo que las instrucciones son correctas, las observaciones fueron atendidas en el último cambio al repositorio, quedo pendiente.

**Comment by az-andresvejar** [comment]
En la linea marcada en azul, se determina como se calcula al ganador, sin embargo, nota lo que dice la parte anterior.
Saludos

**Comment by front4Me** [comment]
@az-andresvejar gracias por responder, ya note mi error, lo mal interprete, subo los cambios necesarios para el código en el último commit, ya debería de calcular bien al ganador.
